kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ClusterRoleBinding
subjects:
  - kind: ServiceAccount
    name: system.serviceaccount.default
    namespace: machine-ns
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
