kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ClusterRoleBinding
subjects
  - kind: ServiceAccount
    name: default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: default-ClusterRole
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ClusterRole
rules:
  - apiGroups: [""]
    verbs: ["get","list"]
