kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machine-RoleBinding
  namespace: machine-ns
subjects:
  - kind: ServiceAccount
    name: fdl
    namespace: machine-ns
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
